### PR TITLE
V6 passive event solution

### LINKED ISSUE #167: Chrome Lighthouse Audit results - Does not use passive listeners to improve scrolling performance
**Describe the bug**
While running a lighthouse audit in Chrome, I'm seeing the "Does not use passive listeners to improve scrolling performance" warning, and it's giving me a 7 point hit on the best practices metric.

I'm assuming there might be some ability to pass this explicitly during the set up of the event handlers, but I was unable to find anywhere in the documentation or source code that pointed me in the right direction.

The component I'm using makes use of the useSwipeable hook rather than the class component, if that matters.

It's also quite possible that I should ignore this aspect of the lighthouse audit.

**Steps or Sandbox to reproduce**
run lighthouse audit on https://ipinder.netlify.com/

**Expected behavior**
I'm assuming there's a simple way to force the event handler to use passive:true, but I was unable to find how to do it in the docs. I would like to avoid this warning in the lighthouse audit.

** Device/Browser **
Chrome 79.0.3945.130
react": "^16.12.0"
react-dom": "^16.12.0"
react-router-dom": "^5.1.2"
react-swipeable": "^5.5.0"

### PR DESCRIPTION
**Pull request by hartzis**
Fixes #167 for v6.

In #167 back in january google introduced a change to lighthouse that nocked 7pts off performance for this issue, here are the changes running lighthouse chrome dev tools on the `examples`:
- Before: 26
- After: 27

I'm theorizing that google realized that nocking 7pts for this issue was a bit ridiculous and have since updated that. 1pt is not something to ignore thought and this should be a good improvement moving forward.

Moved TODOs to v6 branch. Going to cut an alpha release to test with.

### CODE REVIEW

**Review by upatel32 — APPROVED** [review]
This looks awesome! Moving the types to a separate file was a good move, it helps a lot with readability.

File: src/index.ts [hunk 1]
```diff
@@ -202,10 +211,11 @@ function getHandlers(
         [touchMove, onMove],
         [touchEnd, onEnd],
       ];
-      tls.forEach(([e, h]) => el.addEventListener(e, h));
-      // return properly scoped cleanup method for removing listeners
-      return () => tls.forEach(([e, h]) => el.removeEventListener(e, h));
+      tls.forEach(([e, h]) => el.addEventListener(e, h, { passive }));
```
Comment (upatel32) [inline src/index.ts:214]: nice! This seemed like the most straightforward way to go about it
